apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-devsecops-sec
  namespace: sonarqube-devsecops
type: Opaque
data:
  SONARQUBE_JDBC_USERNAME: 
  SONARQUBE_JDBC_PASSWORD: 
  SONARQUBE_JDBC_URL: 
